---
- name: Prepare
  hosts: localhost
  gather_facts: true
  vars:
    go_arch: amd64
    node_exporter_version_windows: 0.18.1
  tasks:
    - name: Download windows_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v{{ node_exporter_version_windows }}/windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        dest: "/tmp/windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      run_once: true
      check_mode: false

    - name: link to node_exporter binaries directory
      become: false
      file:
        src: "/tmp/windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        dest: "/tmp/windows_exporter-{{ go_arch }}.msi"
        state: link
      run_once: true
      check_mode: false

    - name: install pyOpenSSL for certificate generation
      pip:
        name: "pyOpenSSL"

    - name: Create private key
      openssl_privatekey:
        path: "/tmp/tls.key"

    - name: Create CSR
      openssl_csr:
        path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"

    - name: Create certificate
      openssl_certificate:
        path: "/tmp/tls.cert"
        csr_path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"
        provider: selfsigned
