---
- name: Prepare localhost
  hosts: localhost
  gather_facts: false
  vars:
    go_arch: amd64
    node_exporter_version: 0.18.1
  tasks:
    - name: Download node_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      run_once: true
      check_mode: false

    - name: Unpack node_exporter binary
      become: false
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
      run_once: true
      check_mode: false

    - name: link to node_exporter binaries directory
      become: false
      file:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
        dest: "/tmp/node_exporter-linux-amd64"
        state: link
      run_once: true
      check_mode: false

    - name: get collector scripts
      become: false
      get_url:
        url: "{{ item }}"
        dest: "/tmp/{{ item.split('/')[-1] }}"
      with_items:
        - https://raw.githubusercontent.com/prometheus-community/node-exporter-textfile-collector-scripts/master/apt.sh

- name: Prepare instances
  hosts: all
  tasks:
    - name: Install cron
      package:
        name: "{{ 'cronie' if (ansible_os_family | lower == 'redhat') else 'cron' }}"
        state: present
